[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

## Uncomment this and comment the config above to use lld instead of mold
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]